### ISSUE TITLE
QC metrics and filtering pVCF 

### ISSUE THREAD

**Issue by dianacornejo** [statgenetics/UKBB_GWAS_dev#25]
At first, I thought some QC was done in the 200K release of the UKBB. In fact,  I analyzed the variant (vmiss : Proportion of sample missing for every SNP) and sample level missingness (smiss: Proportion of missing SNPs per sample) for the exome data using PLINK. Results are stored here: `/gpfs/gibbs/pi/dewan/data/UKBiobank/results/pca_exomes`

- [x] Add plots

From these results, I could see that there was a very low proportion of samples missing > 2% of their genotypes. Possibly indicating some sort of QC. 

However, official [documentation](https://biobank.ndph.ox.ac.uk/showcase/label.cgi?id=170) from the UKBB indicated that no QC was performed in either the pVCF of the PLINK files.

> Primary and secondary analysis for the UKB 200k release was performed with an updated Functional Equivalence (FE) protocol that retains original quality scores in the CRAM files (referred to as the OQFE protocol, https://www.medrxiv.org/content/10.1101/2020.11.02.20222232v1). The OQFE protocol aligns and duplicate-marks all raw sequencing data (FASTQs) to the full GRCh38 reference in an alt-aware manner as described in the original FE manuscript (https://pubmed.ncbi.nlm.nih.gov/30279509/). The OQFE CRAMs were then called for small variants with DeepVariant to generate per-sample gVCFs. These gVCFs were aggregated and joint-genotyped with GLnexus (https://www.biorxiv.org/content/10.1101/572347v1) to create a single multi-sample VCF (pVCF) for all UKB 200k samples. PLINK files were derived directly from this pVCF. **Please note: to ensure that the UKB 200k data supports a broad range of analyses, no variant- or sample-level filters were pre-applied to the pVCF or PLINK files**. The publicly released pVCF is the direct output of GLnexus, from which the PLINK files are generated. The pVCF contains allele-read depths and genotype qualities for all genotypes from which variant- and sample-level QC metrics can be calculated and to which analysis-specific filters can be applied. Examples of such filtering are described in the UKB 200K preprint (https://www.medrxiv.org/content/10.1101/2020.11.02.20222232v1)

 The goal now is to analyze the pVCF files to calculate QC metrics and filter samples based on results. 
 
 Possible software to use [Hail](https://hail.is/docs/0.2/install/other-cluster.html), [SeqSPARK](https://github.com/statgenetics/seqspark), or maybe if filters are simple enough, just [bcftools](http://samtools.github.io/bcftools/bcftools.html).

**Comment by gaow** [comment]
> Examples of such filtering are described in the UKB 200K preprint

```
A set of QC metrics were applied to the variants included in Table1. Variants that passed the
following criteria are included: individual and variant missingness <10%, Hardy Weinberg
Equilibrium p-value>10^-15, minimum read coverage depth of 7 for SNPs and 10 for indels, at
least one sample per site passed the allele balance threshold > 0.15 for SNPs and 0.20 for
indels. 
```

**Comment by dianacornejo** [comment]
**Plots: maf and missingness per sample and SNP**

![ukb23155_c1_b0_v1 imiss](https://user-images.githubusercontent.com/56558154/108219741-01446700-7104-11eb-84ad-d93d07c27d1f.png)
![ukb23155_c1_b0_v1 lmiss](https://user-images.githubusercontent.com/56558154/108219752-02759400-7104-11eb-8138-e59d39538b7b.png)
![ukb23155_c1_b0_v1 maf](https://user-images.githubusercontent.com/56558154/108219758-043f5780-7104-11eb-9c21-6aed3c68ca99.png)

**Comment by dianacornejo** [comment]
Here, I'll post some resources needed to develop this pipeline and guiding the thinking process for the filtering. 

This is an interesting site to understand how to read a VCF and the metrics given in them fro [GATK](https://sites.google.com/a/broadinstitute.org/legacy-gatk-documentation/frequently-asked-questions/1268-What-is-a-VCF-and-how-should-I-interpret-it)

The docker image that contains the [OQFE](https://hub.docker.com/r/dnanexus/oqfe) pipeline used for the adoption of a standard GRCh38 reference genome with alternate loci, read alignment with BWA-MEM, inclusion of supplementary alignments, duplicate marking that includes the supplementary alignments, CRAM compression and restricted tag usage

An UKBB document on general questions about the 200K exome [release](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwixhImVprrvAhWIc98KHROSAUoQFjABegQIAxAD&url=https%3A%2F%2Fwww.ukbiobank.ac.uk%2Fmedia%2Fcfulxh52%2Fuk-biobank-exome-release-faq_v9-december-2020.pdf&usg=AOvVaw35PM01CquuNGT41Pb_Pyn_)

The [bcftools](http://samtools.github.io/bcftools/bcftools.html#fasta_ref) documentation for QC

**Comment by gaow** [comment]
Thanks @dianacornejo maybe these can all go to the background section for your VCF QC pipeline if you ever decide to make one? I'm not sure if a pipeline is that necessary at this point unless you do the work repeatedly and need to submit to the cluster. You can always come up with a very rough pipeline (eg with hard-coded variable names) and leave it there for others (or yourself) to polish up in the future.

**Comment by dianacornejo** [comment]
Pipeline already generated and tested for production.
