### ISSUE TITLE
Regenie burden - variant classification

### ISSUE THREAD

**Issue by dianacornejo** [statgenetics/UKBB_GWAS_dev#26]
To classify variants for regenie burden test for coding regions. Follow recommendations of [ACMG](https://www.medschool.umaryland.edu/genetic_variant_interpretation_tool1.html/) 
LoF: 
1. nonsense
2. frameshift
3. canonical ±1 or 2 splice sites
4. initiation codon
5. single or multiexon deletion in a gene where LOF is a known mechanism of disease

Annovar [classification](https://annovar.openbioinformatics.org/en/latest/user-guide/gene/) is as follows

1. frameshift insertion
2. frameshit deletion
3. frameshift block substitution
4. stopgain
5. stoploss
6. nonframeshift insertion
7. nonframeshift deletion
8. nonframeshift block substitution
9. nonsynonymous SNV
10. synonymous SNV

**Comment by gaow** [comment]
@dianacornejo thanks! we'll start with the fake mask file, then we'll figure out how to go **from annovar output to that mask file, while incorporating all these information** -- is the text in bold a correct technical summary of what we need to do?

**Comment by dianacornejo** [comment]
@gaow I'm catching up on these issues. I have already finalized the code for the creation of the anno-file, the set_list_file and the mask_file the workflow is `burden_files` in the [annovar.ipynb](https://github.com/cumc/bioworkflows/blob/master/variant-annotation/annovar.ipynb) (it is pretty easy to create depending on whether you use only LoF or LoF and missense variants). For an example see [here](https://rgcgithub.github.io/regenie/options/#burden-testing).
It will be something like this 

```
Mask1 LoF
Mask2 LoF,missense
```

@UxxUnet  see here for explanation on how to convert the annotations from annovar into a format used by regenie burden
