### ISSUE TITLE
Updating finemapping pipeline to include overlapping CS of multiple phenotypes

### ISSUE THREAD

**Issue by tfabiha** [statgenetics/UKBB_GWAS_dev#45]

**Comment by gaow** [comment]
@tfabiha we will need a dedicated step for this and interface to specify results from multiple traits analyzed separately. You can try to design this and run it by us if you want to discuss.

**Comment by tfabiha** [comment]
I chose to create a separate pipeline that takes in as input rds from the univariate finemapping and I've been working on analyzing the phenotypes that way. Should I move these back to the original SuSIE pipeline?

**Comment by gaow** [comment]
No need for now. Let's complete it the way you see fit, then decide where to finalize it at.

**Comment by tfabiha** [comment]
I have an output for overlapping variants in multiple phenotypes, but the same issue will arise as in the finemapping if it's presented in a pptx where not all of the variants will be clearly visible. I'm not sure how to work around that if we present the information in a table. Would it be better to create a graph much like the one in our univariate finemapping (image attached) that will give us the big picture of the overlapping snps while the full information of the positions are stored in a csv file?

<img width="503" alt="Screen Shot 2021-06-05 at 7 03 45 PM" src="https://user-images.githubusercontent.com/32185928/120907580-c1f94200-c630-11eb-906e-e6aa1be74d20.png">

I've also been trying unsuccessfully to create a util.py for the new pipeline so that I don't have function definitions stored in   steps.

**Comment by gaow** [comment]
> Would it be better to create a graph much like the one in our univariate finemapping (image attached) that will give us the big picture of the overlapping snps while the full information of the positions are stored in a csv file?

This is a good idea!

> I've also been trying unsuccessfully to create a util.py for the new pipeline so that I don't have function definitions stored in steps.

For now, you can just try storing functions in the steps if you cannot get it work the other way. We will handle that better when I review your code.

**Comment by tfabiha** [comment]
I've been working more on the pipeline today, fixing previous bugs and trying out different types of graphs to present the data. I've settled on two for now. I haven't been able to add them to the pptx yet because we currently don't have matplotlib in our sif image so I've been testing these locally in a separate notebook.

The first graph is a general summary of the overlapped variants found in each region vs the number of variants (in CS) in each phenotype. I think we would need to place a cap on the number of regions allowed to be depicted in this graph, but this can be chosen by ordering the regions based on the number of overlapped variants.

<img width="923" alt="Screen Shot 2021-06-06 at 6 00 24 PM" src="https://user-images.githubusercontent.com/32185928/120941506-149a3300-c6f1-11eb-8b4d-e41c049f1eaf.png">

The second is a scatterplot per region which shows the pip values of the overlapped regions at the different phenotypes. Currently I'm only using two copies of the same asthma data for my testing so the effect isn't visible. I'm not sure how informative this graph would be.

<img width="751" alt="Screen Shot 2021-06-06 at 6 04 47 PM" src="https://user-images.githubusercontent.com/32185928/120941646-b15cd080-c6f1-11eb-91b7-083691b47d47.png">

I've also adjusted my code so that I can do pairwise overlaps as well to compare the difference in overlap between different pairs of phenotypes, but I can't think of any unique ideas on how to present the data.

**Comment by gaow** [comment]
I like both plots! I dont think we need to go further with pairwise overlaps. They will be special case of the above anyways. Could you try to add matplotlib to the docker image, or you want to provide the command to @dianacornejo to incorporate and update? 

@dianacornejo BTW next time when you update the docker image please use the version of susieR on cran via `install.packages("susieR")`. Thanks!

**Comment by tfabiha** [comment]
I'm still not sure how to update docker so it would be great if @dianacornejo could.

**Comment by gaow** [comment]
@tfabiha please show us the command to include. See what I did above when I ask @dianacornejo to update susieR with cran.

**Comment by tfabiha** [comment]
I'm using two libraries `seaborn` and `matplotlib.pyplot` so would those be `conda install seaborn` and `conda install matplotlib`?

**Comment by tfabiha** [comment]
Diana helped me update the sif image. I've made some fixes and updated the pipeline with the graphs from yesterday. I've also tested this pipeline against the regions Megan pointed out and saw some interesting results. When passing all three phenotypes through there are no overlapping variants. When doing pairwise, asthma and t2d have no overlap either, however asthma and waist, and t2d and waist both produce results from the pipeline.

I've attached the files showing my results here.

[asthma_megan_t2d_megan.overlapped.pptx](https://github.com/statgenetics/UKBB_GWAS_dev/files/6612278/asthma_megan_t2d_megan.overlapped.pptx)
[asthma_megan_waist_megan.overlapped.pptx](https://github.com/statgenetics/UKBB_GWAS_dev/files/6612279/asthma_megan_waist_megan.overlapped.pptx)
[t2d_megan_waist_megan.overlapped.pptx](https://github.com/statgenetics/UKBB_GWAS_dev/files/6612280/t2d_megan_waist_megan.overlapped.pptx)
[t2d_megan_waist_megan_overlapped_variants.csv](https://github.com/statgenetics/UKBB_GWAS_dev/files/6612281/t2d_megan_waist_megan_overlapped_variants.csv)
[asthma_megan_waist_megan_overlapped_variants.csv](https://github.com/statgenetics/UKBB_GWAS_dev/files/6612282/asthma_megan_waist_megan_overlapped_variants.csv)

**Comment by tfabiha** [comment]
I've made some changes to the presentation of the data by adding in an additional graph that shows the fraction wise distribution of the overlap. I've also fixed the limits of the scatterplot so that they are consistent across all regions and more accurately depict the data.

[asthma_megan_waist_megan.overlapped.pptx](https://github.com/statgenetics/UKBB_GWAS_dev/files/6617956/asthma_megan_waist_megan.overlapped.pptx)
[asthma_megan_waist_megan_overlapped_variants.csv](https://github.com/statgenetics/UKBB_GWAS_dev/files/6617957/asthma_megan_waist_megan_overlapped_variants.csv)
[asthma_megan_t2d_megan.overlapped.pptx](https://github.com/statgenetics/UKBB_GWAS_dev/files/6617958/asthma_megan_t2d_megan.overlapped.pptx)
[t2d_megan_waist_megan.overlapped.pptx](https://github.com/statgenetics/UKBB_GWAS_dev/files/6617961/t2d_megan_waist_megan.overlapped.pptx)
[t2d_megan_waist_megan_overlapped_variants.csv](https://github.com/statgenetics/UKBB_GWAS_dev/files/6617962/t2d_megan_waist_megan_overlapped_variants.csv)
