### ISSUE TITLE
Region Extraction

### ISSUE THREAD

**Issue by tfabiha** [statgenetics/UKBB_GWAS_dev#46]
An issue I notice with the pipeline is that it's not really efficient to have the sld and pld be computed at the same step, especially since we only need to use the sld to do the finemapping and computing any ld matrix takes a considerable amount of time for a large number of variants. Previously I removed the pld when doing the extraction for the regions that Megan pointed out so that I could just obtain the output for sld, but for the past couple of hours I've been trying to add the pld in as a separate step computed after the sld.

The file `pre_pop_ld.pickle` is outputted in default_2 but I need to use it for default_4. I haven't been able to find documentation to say how to reference outputs from prior steps, but I've managed a work around that takes the output of the sld step, which is the `sample_ld.gz` file, and edits the file name to end in `pre_pop_ld.pickle`. Conceptually there should be no issues with this because this `pre_pop_ld.pickle` file needs to be outputted for default_2 anyway and so if we get to default_4 the file must exist in the current directory, however this implementation is not as clean as I would like and I'm still looking for a better alternative.

**Comment by tfabiha** [comment]
Submitting the regions Megan pointed out to region extraction to obtain the pld output.

**Comment by gaow** [comment]
>  I haven't been able to find documentation to say how to reference outputs from prior steps

`output_from('default_2')`?  Please try this out.  Let's avoid work arounds that causes the confusion.

**Comment by tfabiha** [comment]
It works. Thank you!
