### ISSUE TITLE
Debugging the VCF_QC_pipeline

### ISSUE THREAD

**Issue by tfabiha** [statgenetics/UKBB_GWAS_dev#49]
I've been setting up my columbia cluster so that I can help Diana with the pipeline. I've had issues setting up github on the cluster but that's resolved right now. Currently I'm trying work through to install JupyterLab and SoS, but I've been having issues with installing and running R.

When running the `R --slave -e "IRkernel::installspec()"` command in the lab wiki I get the error 
`/home/tf2478/miniconda3/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory`. Still reading up on how to fix this.

**Comment by gaow** [comment]
@tfabiha it is never a good idea to install R via conda as of at least last time i tried (2019?). R is available on the cluster. Should be something like `module load R/3.6.1` (or whatever version it is?)

**Comment by tfabiha** [comment]
@gaow that works. Thank you!

**Comment by tfabiha** [comment]
FInished setting up my environment, but having issues with creating an ssh tunnel for jupyter. I keep getting a permission denied error when entering my password. In the processes of communicating with Jose to fix the issue.
