### ISSUE TITLE
Finemapping

### ISSUE THREAD

**Issue by tfabiha** [statgenetics/UKBB_GWAS_dev#50]
@gaow I've been trying to run the finemapping from [here](http://www.christianbenner.com) locally on my mac to test how to use the program. I've dealt with the libraries required to run the program, but I'm unable to run the program even on the sample data provided. I get a non-descriptive `Error : File './example/data' cannot be opened!` error, even with changing my file and folder permissions to 777.

Here is my current directory where I'm working on the file:
<img width="751" alt="Screen Shot 2021-06-10 at 1 03 49 PM" src="https://user-images.githubusercontent.com/32185928/121567203-4dd1ec00-c9ec-11eb-83a4-3c8ff19fc1cf.png">

<img width="751" alt="Screen Shot 2021-06-10 at 1 01 57 PM" src="https://user-images.githubusercontent.com/32185928/121566978-0c414100-c9ec-11eb-9183-22856c819a0f.png">

I've run the following command `./finemap_v1.4_MacOSX --sss --in-files ./example/data`

And this is my error message

<img width="753" alt="Screen Shot 2021-06-10 at 1 05 19 PM" src="https://user-images.githubusercontent.com/32185928/121567403-85d92f00-c9ec-11eb-995d-5e5e783bacd5.png">

**Comment by gaow** [comment]
Good for u! I would not thought of that. I have not ran FINEMAP myself. It would be  very useful if you could figure these out and document in the form of a separate workflow step.
