### ISSUE TITLE
Finemapping Failure at default_1

### ISSUE THREAD

**Issue by tfabiha** [statgenetics/UKBB_GWAS_dev#54]
@gaow the link to the file I started with is [here ](https://github.com/tfabiha/bioworkflows/blob/master/fine-mapping/SuSiE_RSS.ipynb)

I initially started with this file and have been testing and adding to it for the past few days. At first the program ran without issue, but since yesterday I've been seeing the following error

> Error in gzfile(file, mode) : cannot open the connection
Calls: saveRDS -> gzfile
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file '/Users/tfabiha/b/finemapping/results/15_67450330_67578374.Asthma_casesbyICD10codesANDselfreport_controlsbyselfreportandicd10_noautoimmuneincontrols_forbolt030720_ASTHMA.fastGWA.SuSiE_RSS.rds', probable reason 'Operation not permitted'
Execution halted

The program fails at the end of default_1, at the last line, `saveRDS(res, ${_output:r})`. I've been trying to solve the issue by reverting back to this original file but I'm still getting the same error. But since this original file ran without issue initially I'm not sure what's causing the problem.

I did update my docker application yesterday as well, but the docker image that I'm using for default_1 `statisticalgenetics/lmm:2.0` was successfully pulled.

**Comment by gaow** [comment]
@tfabiha i have no idea but why dont' you try something simpler? eg add a line to the workfklow step at the top of the code `saveRDS(1, "test.rds")` see if it saves to the current directory? If so, try to save to the directory in question?

**Comment by gaow** [comment]
> Reading works file but writing to the directory doesn't. I'm not sure why this is an issue now when it wasn't one before.

Is thsi using the code outside SoS , and done on your computer ? The simplest is to remove that folder and rerun the pipeline -- how would that work?

**Comment by tfabiha** [comment]
This is on my computer. I have tried both ways, keeping the folder before running the pipeline and deleting the folder before running the pipeline. I've also tried to set the file permissions of the folder to see if that solved the issue but nothing has worked so far.

**Comment by gaow** [comment]
When the folders are created, could you verify if the permission is indeed a problem ? eg check the user and group that owns the folder, via `ls -l`

**Comment by tfabiha** [comment]
The file permissions are `drwxr-xr-x`

**Comment by gaow** [comment]
No not  the permission, but the user and group that owns the folder. As you can see here only the owner of the folder can write. We need to see who owns it

**Comment by tfabiha** [comment]
Oh I see. My username is the user and the group is `staff`

**Comment by gaow** [comment]
So the owner for that folder is you as `tfabiha`? Then you, as the owner, should be able to write anyting to it?

**Comment by tfabiha** [comment]
Yes that's why I'm confused on why I'm not able to write the file. The container that I use when running the pipeline shouldn't change what user is writing right?

**Comment by gaow** [comment]
> The container that I use when running the pipeline shouldn't change what user is writing right?

it should not if properly mounted, which i can guarantee is the case with Linux but not sure 100% about Mac. However if the folder permission / ownership looks correct then can you try to figure out why you cannot even write to it from your computer locally? 

Another thought: since it is on your laptop you can use either singularity or docker right? They both don't work or you have not tried?

**Comment by tfabiha** [comment]
I have been using docker the entire time for this since it's what worked before. Should I be trying to use singularity?

**Comment by gaow** [comment]
i dont see how it does not work with what you described ... maybe when i have your computer and poke things areound i can tell the issue (after we get back in person!) but for now, yes if you suspect it's permission issue then singularity might be a good check. 

> since it's what worked before.

this is the most puzzling!! and always hard to debug especially wihtout me seeing your computer.
